-- Database of black-and-white nonograms that reward more than 2000 XP.
-- The reason color and B/W nonograms are split is because of the average low
-- amount of XP for B/W nonograms.
-- For adding nonograms that reward less than 2000 XP use "Module:Data/XP_nonograms_bw_other".
-- If a name uses double quotes use a forward slash (e.g. "The "Z" letter" -> "The \"Z\" letter").

-------------------------- ONLY BASE XP FROM NONOGRAMS! -------------------------- 
-- (Without any bonuses, like Fried eggs, Smoothie, Hat of concentration, etc.) --

-- ABOUT NEW XP values:
-- Please add the XP from game version 21.0 in the < new_xp = "", > line.
-- Only yellow and orange dots nonograms have been affected.
-- The values with ~ before are calculated but they are not checked yet.

local nonograms = {
	{
		link            = "[#103298:Zombie]",
		author          = "Draco Machination",
		xp              = "3005",
		new_xp          = "2774",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#166558:A lot of Skulls]",
		author          = "skullgirl",
		xp              = "2983",
		new_xp          = "2754",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#72380:Cat]",
		author          = "SHAMKIREC",
		xp              = "2316",
		new_xp          = "2138",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#50895:Nest]",
		author          = "Street Fighter",
		xp              = "2918",
		new_xp          = "2693",
		size            = "80x76",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#113058:Black Skull 2.0]",
		author          = "skullgirl",
		xp              = "2568",
		new_xp          = "2370",
		size            = "78x80",
		category_1      = "Unreal",
		category_2      = "Painting",
		puzzle_type     = "2",
	},
	{
		link            = "[#162967:ONE PIECE - SANJI]",
		author          = "ayakasumiria",
		xp              = "2488",
		new_xp          = "2297",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#46444:Alice in Wonderland]",
		author          = "Ksana",
		xp              = "2365",
		new_xp          = "2183",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Fantasy",
		puzzle_type     = "2",
	},
	{
		link            = "[#15482:Electrical panel]",
		author          = "krovosos",
		xp              = "2470",
		new_xp          = "2470",
		size            = "80x80",
		category_1      = "Machines",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#112509:Black Skull 1.0]",
		author          = "skullgirl",
		xp              = "3442",
		new_xp          = "3177",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Painting",
		puzzle_type     = "2",
	},
	{
		link            = "[#62684:Lotus flower]",
		author          = "Jobedash",
		xp              = "3609",
		new_xp          = "3331",
		size            = "80x80",
		category_1      = "Flowers",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#86735:CHUNITHM\"Lilyalice Colchicum\"]",
		author          = "KSK_Shizuno",
		xp              = "3010",
		new_xp          = "2779",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Video",
		puzzle_type     = "2",
	},
	{
		link            = "[#41624:Vase with Flowers]",
		author          = "Alexroma5",
		xp              = "2737",
		new_xp          = "2509",
		size            = "80x80",
		category_1      = "Flowers",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#143653:Wreath]",
		author          = "Blooming Lynx",
		xp              = "2641",
		new_xp          = "2421",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "Flowers",
		puzzle_type     = "3",
	},
	{
		link            = "[#150291:Dragon]",
		author          = "DraKay",
		xp              = "2587",
		new_xp          = "2388",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#142003:Swallow on a branch with flowers]",
		author          = "Lisenok_chiffa",
		xp              = "2401",
		new_xp          = "2216",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "Flowers",
		puzzle_type     = "2",
	},
	{
		link            = "[#165683:Mickey to catch a thief]",
		author          = "Mitsakos",
		xp              = "2422",
		new_xp          = "2236",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#164892:Square 10]",
		author          = "Netwale",
		xp              = "2092",
		new_xp          = "2092",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#141516:Spirals]",
		author          = "bobbie420",
		xp              = "2059",
		new_xp          = "2059",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#129883:Snake]",
		author          = "yunzen",
		xp              = "2040",
		new_xp          = "2040",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#85835:Bearclaw]",
		author          = "savrage",
		xp              = "3110",
		new_xp          = "2871",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "Painting",
		puzzle_type     = "2",
	},
	{
		link            = "[#100443:Long is the road]",
		author          = "toufraita2",
		xp              = "2842",
		new_xp          = "2623",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#154317:Tree]",
		author          = "Dragofly",
		xp              = "2616",
		new_xp          = "2415",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#153737:\"Ellen Terry at Age Sixteen\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "2398",
		new_xp          = "2398",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#58252:Tarot - AEther Realm]",
		author          = "TheComet811",
		xp              = "3693",
		new_xp          = "3409",
		size            = "80x80",
		category_1      = "Painting",
		category_2      = "Music",
		puzzle_type     = "2",
	},
	{
		link            = "[#87217:CHUNITHM\"Makino Moco\"]",
		author          = "KSK_Shizuno",
		xp              = "2926",
		new_xp          = "2701",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Video",
		puzzle_type     = "2",
	},
	{
		link            = "[#91493:the most difficult maze]",
		author          = "Sora7",
		xp              = "3776",
		new_xp          = "3485",
		size            = "80x80",
		category_1      = "Adventures",
		category_2      = "Games",
		puzzle_type     = "2",
	},
	{
		link            = "[#135295:Hydra Greek Island]",
		author          = "Anglo.in.Saxony",
		xp              = "2433",
		new_xp          = "2433",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "Adventures",
		puzzle_type     = "1",
	},
	{
		link            = "[#159400:Eagle]",
		author          = "Lisenok_chiffa",
		xp              = "2554",
		new_xp          = "2357",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#103879:Jotaro Kujo]",
		author          = "cl0n3",
		xp              = "2546",
		new_xp          = "2350",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Super",
		puzzle_type     = "2",
	},
	{
		link            = "[#151134:Einstein]",
		author          = "Late555",
		xp              = "2533",
		new_xp          = "2338",
		size            = "80x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#44386:Bastet]",
		author          = "LUNA-CROIX",
		xp              = "2558",
		new_xp          = "2362",
		size            = "80x80",
		category_1      = "Video",
		category_2      = "Egypt",
		puzzle_type     = "2",
	},
	{
		link            = "[#80676:Trippy apple]",
		author          = "Marco818",
		xp              = "2545",
		new_xp          = "2333",
		size            = "80x80",
		category_1      = "Fiction",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#53470:Knight\"3\"]",
		author          = "Alexroma5",
		xp              = "2697",
		new_xp          = "2473",
		size            = "80x80",
		category_1      = "History",
		category_2      = "Weapons",
		puzzle_type     = "3",
	},
	{
		link            = "[#73742:THE EYE!!!!!!!]",
		author          = "Ephemera",
		xp              = "2533",
		new_xp          = "2338",
		size            = "80x80",
		category_1      = "Photorealism",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#53469:Knight\"2\"]",
		author          = "Alexroma5",
		xp              = "2366",
		new_xp          = "2168",
		size            = "80x80",
		category_1      = "History",
		category_2      = "Weapons",
		puzzle_type     = "3",
	},
	{
		link            = "[#165907:Taniwha 2]",
		author          = "Mike1955",
		xp              = "2024",
		new_xp          = "2024",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#152219: Doppo Kunikida]",
		author          = "J0pa",
		xp              = "2567",
		new_xp          = "2370",
		size            = "73x73",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#103228: Cat and birds]",
		author          = "Vincent091",
		xp              = "2504",
		new_xp          = "2311",
		size            = "78x78",
		category_1      = "Cats",
		category_2      = "Nature",
		puzzle_type     = "2",
	},
	{
		link            = "[#168182:Galleon]",
		author          = "Mike1955",
		xp              = "2076",
		new_xp          = "2076",
		size            = "80x80",
		category_1      = "Ships",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#143849:Gintoki-Gintama]",
		author          = "GOOGO",
		xp              = "2296",
		new_xp          = "2119",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#163335:Dog]",
		author          = "the agreste",
		xp              = "2328",
		new_xp          = "2149",
		size            = "80x80",
		category_1      = "Dogs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#149025:Shinobu]",
		author          = "the agreste",
		xp              = "2384",
		new_xp          = "2201",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#86065:BTS]",
		author          = "JennsNonograms",
		xp              = "2295",
		new_xp          = "2118",
		size            = "75x75",
		category_1      = "Symbols",
		category_2      = "Music",
		puzzle_type     = "2",
	},
	{
		link            = "[#169613:Idc anymore]",
		author          = "Dilatoryboi",
		xp              = "2581",
		new_xp          = "2366",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "Space",
		puzzle_type     = "3",
	},
	{
		link            = "[#128615:On a wire]",
		author          = "Claireskee",
		xp              = "2609",
		new_xp          = "2409",
		size            = "75x75",
		category_1      = "Birds",
		category_2      = "Nature",
		puzzle_type     = "2",
	},
	{
		link            = "[#152875:Eyewhirl]",
		author          = "ysamurai",
		xp              = "2614",
		new_xp          = "2396",
		size            = "80x80",
		category_1      = "Painting",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#105948:Galleon]",
		author          = "Draco Machination",
		xp              = "2679",
		new_xp          = "2473",
		size            = "80x80",
		category_1      = "Ships",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#126594:Two dragons]",
		author          = "Osoca",
		xp              = "2373",
		new_xp          = "2191",
		size            = "75x75",
		category_1      = "Dragons",
		category_2      = "Love",
		puzzle_type     = "2",
	},
	{
		link            = "[#47854:ucdevs]",
		author          = "Alexroma5",
		xp              = "2690",
		new_xp          = "2465",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#62993: Satori Komeiji]",
		author          = "SonyNel",
		xp              = "2680",
		new_xp          = "2474",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Video",
		puzzle_type     = "2",
	},
	{
		link            = "[#86706:CHUNITHM\"Astraea\"]",
		author          = "KSK_Shizuno",
		xp              = "2911",
		new_xp          = "2687",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Video",
		puzzle_type     = "2",
	},
	{
		link            = "[#34376:Spanish' castle]",
		author          = "stoerne",
		xp              = "2233",
		new_xp          = "2061",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "History",
		puzzle_type     = "2",
	},
	{
		link            = "[#145108:Dragon]",
		author          = "AJ7411",
		xp              = "2842",
		new_xp          = "2624",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#92880:Fubuki (One Punch Man)]",
		author          = "Swapnil Bankar",
		xp              = "2286",
		new_xp          = "2110",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#155515:+++Squares 107]",
		author          = "kata57",
		xp              = "2232",
		new_xp          = "2232",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#171062:Chessboard]",
		author          = "Marcopei",
		xp              = "2618",
		new_xp          = "2416",
		size            = "80x80",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#159008:Tanjiro]",
		author          = "the agreste",
		xp              = "2647",
		new_xp          = "2443",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#40278:Somewhere in Venice]",
		author          = "belko61",
		xp              = "2374",
		new_xp          = "2374",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "Around",
		puzzle_type     = "4",
	},
	{
		link            = "[#148157:OOT Triforce]",
		author          = "Rv_",
		xp              = "2554",
		new_xp          = "2341",
		size            = "80x80",
		category_1      = "Video",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#118383:Cosmonautics Day April 12]",
		author          = "Malevich)",
		xp              = "2153",
		new_xp          = "2153",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Space",
		puzzle_type     = "1",
	},
	{
		link            = "[#49140:Little Red Riding Hood]",
		author          = "Alexroma5",
		xp              = "2103",
		new_xp          = "2103",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Fantasy",
		puzzle_type     = "4",
	},
	{
		link            = "[#53394:Ancient city]",
		author          = "Alexroma5",
		xp              = "2517",
		new_xp          = "2307",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "Around",
		puzzle_type     = "3",
	},
	{
		link            = "[#61834:SUDOKU]",
		author          = "unko",
		xp              = "2807",
		new_xp          = "2573",
		size            = "77x77",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#169782:Captain America]",
		author          = "eyco",
		xp              = "2271",
		new_xp          = "2096",
		size            = "80x76",
		category_1      = "Cartoon",
		category_2      = "Super",
		puzzle_type     = "2",
	},
	{
		link            = "[#86690:Italian street]",
		author          = "Anita Kendrick",
		xp              = "3193",
		new_xp          = "2948",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#86705:maimai\"Otohime\"]",
		author          = "KSK_Shizuno",
		xp              = "2567",
		new_xp          = "2369",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Video",
		puzzle_type     = "2",
	},
	{
		link            = "[#115081:CHUNITHM\"Hakobe Naru\"]",
		author          = "KSK_Shizuno",
		xp              = "2685",
		new_xp          = "2478",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Video",
		puzzle_type     = "2",
	},
	{
		link            = "[#59377:Dino egg hatching]",
		author          = "Jobedash",
		xp              = "2432",
		new_xp          = "2432",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#143185:Sudoku figura]",
		author          = "Woleen",
		xp              = "2758",
		new_xp          = "2546",
		size            = "77x77",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#65651:Fisherman and the Golden Fish]",
		author          = "belko61",
		xp              = "2083",
		new_xp          = "2083",
		size            = "70x80",
		category_1      = "Fantasy",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#102708:Cat face]",
		author          = "Vincent091",
		xp              = "2497",
		new_xp          = "2305",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#60614:Nonograms Katana]",
		author          = "SonyNel",
		xp              = "2930",
		new_xp          = "2705",
		size            = "80x80",
		category_1      = "Symbols",
		category_2      = "Games",
		puzzle_type     = "2",
	},
	{
		link            = "[#65642:RPG Character]",
		author          = "belko61",
		xp              = "2036",
		new_xp          = "2036",
		size            = "70x80",
		category_1      = "Video",
		category_2      = "Fantasy",
		puzzle_type     = "4",
	},
	{
		link            = "[#102782:Ilya Muromets]",
		author          = "belko61",
		xp              = "2109",
		new_xp          = "2109",
		size            = "70x80",
		category_1      = "Fantasy",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#79800:Church]",
		author          = "Alud",
		xp              = "2556",
		new_xp          = "2343",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "History",
		puzzle_type     = "3",
	},
	{
		link            = "[#134407:Millenium falcon]",
		author          = "Victor Azevedo",
		xp              = "2224",
		new_xp          = "2053",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Fiction",
		puzzle_type     = "2",
	},
	{
		link            = "[#118928:ONE PIECE TRAFALGAR-LAW]",
		author          = "ayakasumiria",
		xp              = "2216",
		new_xp          = "2046",
		size            = "80x78",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#61331:Knight 5]",
		author          = "Alexroma5",
		xp              = "2127",
		new_xp          = "2127",
		size            = "79x79",
		category_1      = "Adventures",
		category_2      = "Weapons",
		puzzle_type     = "0",
	},
	{
		link            = "[#118092:Tree of life]",
		author          = "muttn",
		xp              = "2386",
		new_xp          = "2203",
		size            = "75x75",
		category_1      = "Plants",
		category_2      = "Nature",
		puzzle_type     = "2",
	},
	{
		link            = "[#173296:Looking at sunset]",
		author          = "toufraita2",
		xp              = "2971",
		new_xp          = "2743",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Twilight",
		puzzle_type     = "2",
	},
	{
		link            = "[#87752:Saber-toothed Tiger]",
		author          = "belko61",
		xp              = "2174",
		new_xp          = "2174",
		size            = "80x75",
		category_1      = "Unreal",
		category_2      = "Animals",
		puzzle_type     = "1",
	},
	{
		link            = "[#171208:Easter]",
		author          = "Ella07",
		xp              = "2425",
		new_xp          = "2239",
		size            = "80x80",
		category_1      = "Holidays",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#70605:Joker]",
		author          = "Jobedash",
		xp              = "3285",
		new_xp          = "3032",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "People",
		puzzle_type     = "2",
	},
	{
		link            = "[#100227:Scarlett and Rett]",
		author          = "SalAlex",
		xp              = "2233",
		new_xp          = "2061",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "People",
		puzzle_type     = "2",
	},
	{
		link            = "[#102777:Pianist]",
		author          = "belko61",
		xp              = "2279",
		new_xp          = "2279",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Music",
		puzzle_type     = "1",
	},
	{
		link            = "[#143075:Maze]",
		author          = "Woleen",
		xp              = "2844",
		new_xp          = "2625",
		size            = "80x80",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#149973:Crocodile 2]",
		author          = "AJ7411",
		xp              = "2516",
		new_xp          = "2322",
		size            = "80x80",
		category_1      = "Fish",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#103950:Shion]",
		author          = "EeveeArc",
		xp              = "2353",
		new_xp          = "2157",
		size            = "80x80",
		category_1      = "Video",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#104719:a scared girl running]",
		author          = "ambrine",
		xp              = "2622",
		new_xp          = "2420",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "People",
		puzzle_type     = "2",
	},
	{
		link            = "[#101476:Love80]",
		author          = "bobbieann",
		xp              = "2659",
		new_xp          = "2437",
		size            = "80x80",
		category_1      = "Love",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#55385:Chess]",
		author          = "KillTheRico",
		xp              = "2552",
		new_xp          = "2356",
		size            = "80x80",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#154440:e2e4]",
		author          = "SID",
		xp              = "2595",
		new_xp          = "2395",
		size            = "80x80",
		category_1      = "Games",
		category_2      = "Sport",
		puzzle_type     = "2",
	},
	{
		link            = "[#57372:Daisy in the meadow]",
		author          = "Jobedash",
		xp              = "2940",
		new_xp          = "2713",
		size            = "80x80",
		category_1      = "Flowers",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#79112:Mermaid 2.0]",
		author          = "Jobedash",
		xp              = "2912",
		new_xp          = "2688",
		size            = "80x80",
		category_1      = "Fantasy",
		category_2      = "Unreal",
		puzzle_type     = "2",
	},
	{
		link            = "[#87355:CHUNITHM\"Chocolat\"]",
		author          = "KSK_Shizuno",
		xp              = "2521",
		new_xp          = "2311",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Video",
		puzzle_type     = "3",
	},
	{
		link            = "[#36578:Cosmonaut]",
		author          = "belko61",
		xp              = "2064",
		new_xp          = "2064",
		size            = "75x80",
		category_1      = "People",
		category_2      = "Space",
		puzzle_type     = "1",
	},
	{
		link            = "[#61873:Bird]",
		author          = "SonyNel",
		xp              = "2172",
		new_xp          = "2005",
		size            = "80x74",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#162307:gintoki-gintama]",
		author          = "GOOGO",
		xp              = "2384",
		new_xp          = "2201",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#147204:Movie]",
		author          = "AJ7411",
		xp              = "2283",
		new_xp          = "2107",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Animals",
		puzzle_type     = "2",
	},
	{
		link            = "[#135889:Irbis]",
		author          = "belko61",
		xp              = "2004",
		new_xp          = "2004",
		size            = "80x75",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#141636:House]",
		author          = "chibis",
		xp              = "2482",
		new_xp          = "2482",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#47851:Italian landscape]",
		author          = "Alexroma5",
		xp              = "2489",
		new_xp          = "2282",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Around",
		puzzle_type     = "3",
	},
	{
		link            = "[#63268:Moana]",
		author          = "Jobedash",
		xp              = "2688",
		new_xp          = "2464",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Movies",
		puzzle_type     = "3",
	},
	{
		link            = "[#87004:CHUNITHM\"Amano Ai\"]",
		author          = "KSK_Shizuno",
		xp              = "2735",
		new_xp          = "2525",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Video",
		puzzle_type     = "2",
	},
	{
		link            = "[#172186:Mother of the Universe]",
		author          = "AshenThrone",
		xp              = "2310",
		new_xp          = "2132",
		size            = "80x80",
		category_1      = "Fiction",
		category_2      = "Space",
		puzzle_type     = "2",
	},
	{
		link            = "[#135778:Xenomorph (Alien)]",
		author          = "Crep",
		xp              = "2475",
		new_xp          = "2285",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Unreal",
		puzzle_type     = "2",
	},
	{
		link            = "[#36060:Zebra]",
		author          = "Alexroma5",
		xp              = "2488",
		new_xp          = "2297",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#43598:Marvin the Martian]",
		author          = "pharmadrum",
		xp              = "3088",
		new_xp          = "2850",
		size            = "80x74",
		category_1      = "Cartoon",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#134694:Gnomes1]",
		author          = "Nana57",
		xp              = "3010",
		new_xp          = "2778",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#122085:Dream of fishing]",
		author          = "mortyrus",
		xp              = "2964",
		new_xp          = "2736",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Games",
		puzzle_type     = "2",
	},
	{
		link            = "[#135929:Over the horizon]",
		author          = "L E B lll A",
		xp              = "2854",
		new_xp          = "2634",
		size            = "80x80",
		category_1      = "Twilight",
		category_2      = "Ships",
		puzzle_type     = "2",
	},
	{
		link            = "[#27773:Flower Basket]",
		author          = "belko61",
		xp              = "2757",
		new_xp          = "2545",
		size            = "80x75",
		category_1      = "Flowers",
		category_2      = "Painting",
		puzzle_type     = "2",
	},
	{
		link            = "[#147453:Paper Games: Hangman]",
		author          = "ErinAero1",
		xp              = "2746",
		new_xp          = "2535",
		size            = "80x80",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#139394:Church3]",
		author          = "bobbie420",
		xp              = "2740",
		new_xp          = "2511",
		size            = "75x80",
		category_1      = "Houses",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#141767:House in the village]",
		author          = "chibis",
		xp              = "2717",
		new_xp          = "2717",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#41146:Egypt]",
		author          = "Alexroma5",
		xp              = "2602",
		new_xp          = "2385",
		size            = "78x74",
		category_1      = "Egypt",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#42614:Pheasant]",
		author          = "Alexroma5",
		xp              = "2582",
		new_xp          = "2384",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#155395:+++Squares 104]",
		author          = "kata57",
		xp              = "2525",
		new_xp          = "2525",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#154124:+++Squares 92]",
		author          = "kata57",
		xp              = "2485",
		new_xp          = "2485",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#98551:7x7 tank nonogram in nonogram]",
		author          = "TRico2",
		xp              = "2463",
		new_xp          = "2463",
		size            = "80x80",
		category_1      = "Games",
		category_2      = "Weapons",
		puzzle_type     = "0",
	},
	{
		link            = "[#124730:On the tree hammock]",
		author          = "Claireskee",
		xp              = "2442",
		new_xp          = "2254",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "People",
		puzzle_type     = "2",
	},
	{
		link            = "[#151442:+++Squares 36]",
		author          = "kata57",
		xp              = "2439",
		new_xp          = "2439",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#36730:year of the rooster]",
		author          = "Alexroma5",
		xp              = "2430",
		new_xp          = "2243",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#112185:Mt.fuji & wave]",
		author          = "cure grace",
		xp              = "2426",
		new_xp          = "2240",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Painting",
		puzzle_type     = "2",
	},
	{
		link            = "[#73194:Deer]",
		author          = "belko61",
		xp              = "2419",
		new_xp          = "2419",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#150391:+++Squares 10]",
		author          = "kata57",
		xp              = "2412",
		new_xp          = "2412",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#74455:The last tree...]",
		author          = "Malgoska",
		xp              = "2398",
		new_xp          = "2398",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#86268:Neuschwanstein]",
		author          = "Anglo.in.Saxony",
		xp              = "2372",
		new_xp          = "2372",
		size            = "80x80",
		category_1      = "Around",
		category_2      = "Adventures",
		puzzle_type     = "1",
	},
	{
		link            = "[#141768:Forest]",
		author          = "chibis",
		xp              = "2361",
		new_xp          = "2361",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "Nature",
		puzzle_type     = "1",
	},
	{
		link            = "[#98137:Grape Wine]",
		author          = "belko61",
		xp              = "2360",
		new_xp          = "2360",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "Food",
		puzzle_type     = "1",
	},
	{
		link            = "[#162387:+++Squares 151]",
		author          = "kata57",
		xp              = "2357",
		new_xp          = "2357",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#92342:Tower]",
		author          = "L E B lll A",
		xp              = "2352",
		new_xp          = "2171",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "Houses",
		puzzle_type     = "2",
	},
	{
		link            = "[#150354:+++Squares 6]",
		author          = "kata57",
		xp              = "2347",
		new_xp          = "2347",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#151103:+++Squares 26]",
		author          = "kata57",
		xp              = "2340",
		new_xp          = "2340",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#81277:Pretty Cow]",
		author          = "belko61",
		xp              = "2339",
		new_xp          = "2339",
		size            = "80x75",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#97852:Miller's House]",
		author          = "Alud",
		xp              = "2331",
		new_xp          = "2331",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Houses",
		puzzle_type     = "1",
	},
	{
		link            = "[#150378:Asymetrics squares]",
		author          = "Nomase",
		xp              = "2327",
		new_xp          = "2327",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#36582:Shere Khan]",
		author          = "belko61",
		xp              = "2322",
		new_xp          = "2322",
		size            = "75x75",
		category_1      = "Cartoon",
		category_2      = "Animals",
		puzzle_type     = "1",
	},
	{
		link            = "[#61049:Dragon Gorynych]",
		author          = "belko61",
		xp              = "2310",
		new_xp          = "2310",
		size            = "80x80",
		category_1      = "Fantasy",
		category_2      = "Dragons",
		puzzle_type     = "4",
	},
	{
		link            = "[#88994:Sirin]",
		author          = "belko61",
		xp              = "2305",
		new_xp          = "2305",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "History",
		puzzle_type     = "4",
	},
	{
		link            = "[#169575:Hourglass Segment]",
		author          = "Mike1955",
		xp              = "2301",
		new_xp          = "2301",
		size            = "80x80",
		category_1      = "Objects",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#152765:+++Squares 61]",
		author          = "kata57",
		xp              = "2290",
		new_xp          = "2290",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#145741:Amsterdam at sunset, in B&W]",
		author          = "Vladimir Grachev",
		xp              = "2288",
		new_xp          = "2288",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#165651:Steamboat Willie 2]",
		author          = "Anglo.in.Saxony",
		xp              = "2281",
		new_xp          = "2281",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Animals",
		puzzle_type     = "1",
	},
	{
		link            = "[#149895:Giraffe]",
		author          = "Pawn_b4",
		xp              = "2269",
		new_xp          = "2269",
		size            = "75x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#41193:Girl]",
		author          = "Alexroma5",
		xp              = "2265",
		new_xp          = "2090",
		size            = "80x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#9169:Castle]",
		author          = "Street Fighter",
		xp              = "2234",
		new_xp          = "2234",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#74184:In the rushes.]",
		author          = "Malgoska",
		xp              = "2229",
		new_xp          = "2043",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "Nature",
		puzzle_type     = "3",
	},
	{
		link            = "[#152111:Iguro]",
		author          = "the agreste",
		xp              = "2226",
		new_xp          = "2040",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#75283:Checkers]",
		author          = "Terry Boot",
		xp              = "2214",
		new_xp          = "2044",
		size            = "72x72",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#70386:Maze]",
		author          = "Overland",
		xp              = "2210",
		new_xp          = "2210",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#113532:Patterns]",
		author          = "Jajajajaja248",
		xp              = "2203",
		new_xp          = "2203",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#126239:Tsar Terem]",
		author          = "belko61",
		xp              = "2194",
		new_xp          = "2194",
		size            = "80x70",
		category_1      = "Houses",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#152087:+++Squares 48]",
		author          = "kata57",
		xp              = "2182",
		new_xp          = "2182",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#114853:Waterfall]",
		author          = "belko61",
		xp              = "2182",
		new_xp          = "2182",
		size            = "75x80",
		category_1      = "Nature",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#130712:Yoshijage Kira Jojo4]",
		author          = "utenanana",
		xp              = "2170",
		new_xp          = "2170",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "0",
	},
	{
		link            = "[#141553:Village]",
		author          = "chibis",
		xp              = "2169",
		new_xp          = "2169",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Houses",
		puzzle_type     = "1",
	},
	{
		link            = "[#165114:Kahu Hawk]",
		author          = "Mike1955",
		xp              = "2077",
		new_xp          = "2077",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#150303:+++Squares 7]",
		author          = "kata57",
		xp              = "2073",
		new_xp          = "2073",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#70655:Vulture]",
		author          = "belko61",
		xp              = "2071",
		new_xp          = "2071",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#152444:+++Squares 63]",
		author          = "kata57",
		xp              = "2058",
		new_xp          = "2058",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#154624:+++Squares 99]",
		author          = "kata57",
		xp              = "2058",
		new_xp          = "2058",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#98130:Grape Harvest]",
		author          = "belko61",
		xp              = "2054",
		new_xp          = "2054",
		size            = "70x80",
		category_1      = "Plants",
		category_2      = "People",
		puzzle_type     = "1",
	},
	{
		link            = "[#151088:+++Squares 23]",
		author          = "kata57",
		xp              = "2052",
		new_xp          = "2052",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#59245:Dance]",
		author          = "belko61",
		xp              = "2001",
		new_xp          = "2001",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Music",
		puzzle_type     = "0",
	},
	{
		link            = "[#172844:Castle]",
		author          = "lost6590",
		xp              = "2242",
		new_xp          = "2070",
		size            = "60x80",
		category_1      = "Houses",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#176071:Medieval castle l]",
		author          = "Dimsum",
		xp              = "2541",
		new_xp          = "2329",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "History",
		puzzle_type     = "3",
	},
	{
		link            = "[#174168:Discworld 26]",
		author          = "Lisenok_chiffa",
		xp              = "2741",
		new_xp          = "2530",
		size            = "80x80",
		category_1      = "Fantasy",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#190178:Christmas tree]",
		author          = "simsomyung",
		xp              = "3240",
		new_xp          = "2991",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "Holidays",
		puzzle_type     = "2",
	},
	{
		link            = "[#185477:Dragon]",
		author          = "iltarusko",
		xp              = "3045",
		new_xp          = "2810",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#181023:The angel]",
		author          = "iltarusko",
		xp              = "3028",
		new_xp          = "2795",
		size            = "80x80",
		category_1      = "History",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#199982:twinkle twinkle little star]",
		author          = "Jin Taesoo",
		xp              = "3635",
		new_xp          = "3356",
		size            = "80x80",
		category_1      = "Symbols",
		category_2      = "Music",
		puzzle_type     = "2",
	},
	{
		link            = "[#196360:Classical Building]",
		author          = "Forest Cat",
		xp              = "3092",
		new_xp          = "2834",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "History",
		puzzle_type     = "3",
	},
	{
		link            = "[#185504:Mother of Dragons]",
		author          = "iltarusko",
		xp              = "3074",
		new_xp          = "2838",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Dragons",
		puzzle_type     = "2",
	},
	{
		link            = "[#144301:Modern sonic]",
		author          = "nessdabest",
		xp              = "3014",
		new_xp          = "2782",
		size            = "80x80",
		category_1      = "Video",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#138694:Mary at the cross]",
		author          = "goije",
		xp              = "2055",
		new_xp          = "2055",
		size            = "80x80",
		category_1      = "History",
		category_2      = "Holidays",
		puzzle_type     = "1",
	},
	{
		link            = "[#146737:Animal]",
		author          = "AJ7411",
		xp              = "2621",
		new_xp          = "2420",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#183573:Anxiety]",
		author          = "iltarusko",
		xp              = "3022",
		new_xp          = "2790",
		size            = "80x80",
		category_1      = "Smiles",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#195912:Humming Bird]",
		author          = "Mike1955",
		xp              = "2096",
		new_xp          = "2096",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "Flowers",
		puzzle_type     = "1",
	},
	{
		link            = "[#39061:Chess]",
		author          = "MasterAlex",
		xp              = "2172",
		new_xp          = "2172",
		size            = "80x80",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#187748:List of 60 MP]",
		author          = "Effti",
		xp              = "2247",
		new_xp          = "2247",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#40433:tigress]",
		author          = "Alexroma5",
		xp              = "2225",
		new_xp          = "2054",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#147286:Animal]",
		author          = "AJ7411",
		xp              = "2264",
		new_xp          = "2076",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#186918:David and Goliath]",
		author          = "Konig",
		xp              = "2719",
		new_xp          = "2509",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "2",
	},
	{
		link            = "[#154950:++No Squares 7]",
		author          = "kata57",
		xp              = "2322",
		new_xp          = "2322",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#182075:Elegant lady]",
		author          = "iltarusko",
		xp              = "2912",
		new_xp          = "2688",
		size            = "80x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#145338:Pokemon]",
		author          = "AJ7411",
		xp              = "2209",
		new_xp          = "2039",
		size            = "73x80",
		category_1      = "Super",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#185480:Dragon II]",
		author          = "iltarusko",
		xp              = "2361",
		new_xp          = "2180",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#180719:Bride]",
		author          = "iltarusko",
		xp              = "2729",
		new_xp          = "2519",
		size            = "80x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#158515:Geralt of Rivia]",
		author          = "Aorlinn",
		xp              = "2851",
		new_xp          = "2613",
		size            = "80x80",
		category_1      = "Fantasy",
		category_2      = "People",
		puzzle_type     = "3",
	},
	{
		link            = "[#94979:Mandala]",
		author          = "SaraLW",
		xp              = "2078",
		new_xp          = "2078",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#193755:Horse 2]",
		author          = "Dark_Angel",
		xp              = "2352",
		new_xp          = "2171",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#208469:Different things 80x80]",
		author          = "Goose1",
		xp              = "2982",
		new_xp          = "2753",
		size            = "80x80",
		category_1      = "Adventures",
		category_2      = "Pirates",
		puzzle_type     = "2",
	},
	{
		link            = "[#207615:Spitz]",
		author          = "yagr",
		xp              = "2649",
		new_xp          = "2445",
		size            = "80x80",
		category_1      = "Dogs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#207651:Falcon]",
		author          = "yagr",
		xp              = "2192",
		new_xp          = "2010",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#207616:Tiger]",
		author          = "yagr",
		xp              = "2779",
		new_xp          = "2565",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#204473:Dragon]",
		author          = "yagr",
		xp              = "2561",
		new_xp          = "2364",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#205915:Manul]",
		author          = "yagr",
		xp              = "2391",
		new_xp          = "2207",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#206129:Lynx]",
		author          = "yagr",
		xp              = "2290",
		new_xp          = "2114",
		size            = "74x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#211153:Different things 80x80]",
		author          = "Goose1",
		xp              = "2407",
		new_xp          = "2222",
		size            = "80x80",
		category_1      = "Fish",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#205413:American Bulldog]",
		author          = "yagr",
		xp              = "2173",
		new_xp          = "2006",
		size            = "80x80",
		category_1      = "Dogs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#204732:Summer on the beach]",
		author          = "blinchoff",
		xp              = "2489",
		new_xp          = "2297",
		size            = "60x80",
		category_1      = "Nature",
		category_2      = "Twilight",
		puzzle_type     = "2",
	},
	{
		link            = "[#207688:Different things 80x80]",
		author          = "Goose1",
		xp              = "2603",
		new_xp          = "2403",
		size            = "80x80",
		category_1      = "Fish",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#203202:sick, twisted, demented]",
		author          = "Psexanutik",
		xp              = "2243",
		new_xp          = "2070",
		size            = "60x80",
		category_1      = "People",
		category_2      = "Smiles",
		puzzle_type     = "2",
	},
	{
		link            = "[#204196:Ace One Piece]",
		author          = "henri1673",
		xp              = "2522",
		new_xp          = "2328",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#205109:Fox cub]",
		author          = "Jan Kokto",
		xp              = "2675",
		new_xp          = "2452",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#205462:Girl with big curls]",
		author          = "Jan Kokto",
		xp              = "2525",
		new_xp          = "2331",
		size            = "80x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#208874:Punisher - Frank Castle]",
		author          = "Crep",
		xp              = "2761",
		new_xp          = "2548",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Super",
		puzzle_type     = "2",
	},
	{
		link            = "[#128031:(G)I-DLE Soyeon]",
		author          = "GM Roach",
		xp              = "2633",
		new_xp          = "2430",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Music",
		puzzle_type     = "2",
	},
	{
		link            = "[#183672:Peaceful moment]",
		author          = "iltarusko",
		xp              = "2808",
		new_xp          = "2592",
		size            = "80x80",
		category_1      = "Objects",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#188582:Winter night]",
		author          = "iltarusko",
		xp              = "2485",
		new_xp          = "2294",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Twilight",
		puzzle_type     = "2",
	},
	{
		link            = "[#192620:Fairy]",
		author          = "iltarusko",
		xp              = "2685",
		new_xp          = "2479",
		size            = "80x80",
		category_1      = "Fantasy",
		category_2      = "Unreal",
		puzzle_type     = "2",
	},
	{
		link            = "[#202477:To bee or not to bee]",
		author          = "The Rabbit",
		xp              = "2738",
		new_xp          = "2528",
		size            = "80x80",
		category_1      = "Insects",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#207807:Tiger]",
		author          = "yagr",
		xp              = "2187",
		new_xp          = "2018",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#211086:Cat. Frenzy]",
		author          = "Jan Kokto",
		xp              = "2387",
		new_xp          = "2188",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#132411:Cat from Hell]",
		author          = "Jan Kokto",
		xp              = "2220",
		new_xp          = "2035",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#172178:anime girl]",
		author          = "Feodor2020",
		xp              = "2463",
		new_xp          = "2273",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#179121:Lifecircle]",
		author          = "iltarusko",
		xp              = "2387",
		new_xp          = "2188",
		size            = "80x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#180736:Tex Willer]",
		author          = "iltarusko",
		xp              = "2705",
		new_xp          = "2497",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "People",
		puzzle_type     = "2",
	},
	{
		link            = "[#185621:Lady in a evening gown]",
		author          = "iltarusko",
		xp              = "2658",
		new_xp          = "2453",
		size            = "80x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#188032:Unimaginable suffering]",
		author          = "Anowyn",
		xp              = "2388",
		new_xp          = "2204",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Around",
		puzzle_type     = "2",
	},
	{
		link            = "[#209103:A dinosaur in the forest]",
		author          = "artbyROO",
		xp              = "2426",
		new_xp          = "2224",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "Nature",
		puzzle_type     = "3",
	},
	{
		link            = "[#46441:Alice in Wonderland]",
		author          = "Ksana",
		xp              = "2264",
		new_xp          = "2090",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Fantasy",
		puzzle_type     = "2",
	},
	{
		link            = "[#82538:The Kraken]",
		author          = "Marco818",
		xp              = "2652",
		new_xp          = "2448",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Ships",
		puzzle_type     = "2",
	},
	{
		link            = "[#99747:Yodo Boruto]",
		author          = "XIII",
		xp              = "2702",
		new_xp          = "2495",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#146431:Pokemon]",
		author          = "AJ7411",
		xp              = "2226",
		new_xp          = "2054",
		size            = "80x70",
		category_1      = "Super",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#145126:Kid Trunks ss]",
		author          = "AJ7411",
		xp              = "2596",
		new_xp          = "2396",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#147884:Simba 3]",
		author          = "AJ7411",
		xp              = "2555",
		new_xp          = "2358",
		size            = "80x77",
		category_1      = "Cartoon",
		category_2      = "Animals",
		puzzle_type     = "2",
	},
	{
		link            = "[#189159:86]",
		author          = "rphii",
		xp              = "2635",
		new_xp          = "2415",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#212748:Frog souls]",
		author          = "Goose1",
		xp              = "3323",
		new_xp          = "3068",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Fish",
		puzzle_type     = "2",
	},
	{
		link            = "[#213576:Different things 80x80]",
		author          = "Goose1",
		xp              = "3047",
		new_xp          = "2813",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Around",
		puzzle_type     = "2",
	},
	{
		link            = "[#214671:Mega-pazle]",
		author          = "Goose1",
		xp              = "3485",
		new_xp          = "3217",
		size            = "80x80",
		category_1      = "Video",
		category_2      = "Games",
		puzzle_type     = "2",
	},
	{
		link            = "[#214870:Different things 80x80]",
		author          = "Goose1",
		xp              = "3241",
		new_xp          = "2991",
		size            = "80x80",
		category_1      = "Fish",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#19748:Font]",
		author          = "ladyfermata",
		xp              = "3156",
		new_xp          = "2893",
		size            = "80x80",
		category_1      = "Symbols",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#33965:Patchwork (hard)]",
		author          = "Zelie",
		xp              = "3070",
		new_xp          = "2834",
		size            = "80x80",
		category_1      = "Symbols",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#218144:One Piece Nika]",
		author          = "fdra",
		xp              = "3254",
		new_xp          = "3003",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#226001:puzzle]",
		author          = "Goose1",
		xp              = "3526",
		new_xp          = "3255",
		size            = "80x80",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#206038:Saint Bernard]",
		author          = "yagr",
		xp              = "2636",
		new_xp          = "2433",
		size            = "80x80",
		category_1      = "Dogs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#231886:Sugar Skull]",
		author          = "Ephemera",
		xp              = "3264",
		new_xp          = "3013",
		size            = "80x80",
		category_1      = "History",
		category_2      = "Holidays",
		puzzle_type     = "2",
	},
	{
		link            = "[#187107:Tiger]",
		author          = "Anowyn",
		xp              = "2457",
		new_xp          = "2253",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#40284:Locomotive]",
		author          = "belko61",
		xp              = "2087",
		new_xp          = "2087",
		size            = "80x80",
		category_1      = "Adventures",
		category_2      = "Transport",
		puzzle_type     = "1",
	},
	{
		link            = "[#220521:Big Ben]",
		author          = "Arteliist",
		xp              = "2230",
		new_xp          = "2230",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "Around",
		puzzle_type     = "1",
	},
	{
		link            = "[#213464:Cat]",
		author          = "Glotecir",
		xp              = "2474",
		new_xp          = "2284",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#208324:Flower girl]",
		author          = "Mike1955",
		xp              = "2066",
		new_xp          = "2066",
		size            = "80x80",
		category_1      = "Flowers",
		category_2      = "People",
		puzzle_type     = "1",
	},
	{
		link            = "[#26164:Drakkar]",
		author          = "belko61",
		xp              = "2159",
		new_xp          = "2159",
		size            = "75x80",
		category_1      = "Ships",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#151507:Dog]",
		author          = "AJ7411",
		xp              = "2193",
		new_xp          = "2010",
		size            = "80x80",
		category_1      = "Dogs",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#149856:Butterfly 9]",
		author          = "AJ7411",
		xp              = "2396",
		new_xp          = "2197",
		size            = "80x80",
		category_1      = "Insects",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#223264:Darkwing Duck]",
		author          = "ChefSloth",
		xp              = "2781",
		new_xp          = "2568",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Super",
		puzzle_type     = "2",
	},
	{
		link            = "[#232545:Vongola (KHR)]",
		author          = "erikarasik",
		xp              = "2279",
		new_xp          = "2089",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#232771:District 1 \"hunger games\"]",
		author          = "erikarasik",
		xp              = "2377",
		new_xp          = "2179",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#232800:District 2 \"hunger games\"]",
		author          = "erikarasik",
		xp              = "2474",
		new_xp          = "2268",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#232808:District 3 \"hunger games\"]",
		author          = "erikarasik",
		xp              = "2477",
		new_xp          = "2271",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#232645:Capital \"hunger games\"]",
		author          = "erikarasik",
		xp              = "2396",
		new_xp          = "2197",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#232942:District 8 \"hunger games\"]",
		author          = "erikarasik",
		xp              = "2308",
		new_xp          = "2116",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#232895:District 5 \"hunger games\"]",
		author          = "erikarasik",
		xp              = "2430",
		new_xp          = "2228",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#232902:District 6 \"hunger games\"]",
		author          = "erikarasik",
		xp              = "2339",
		new_xp          = "2144",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#226042:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2255",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#229931:\"Gentleness\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2509",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#235782:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2227",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "Unreal",
		puzzle_type     = "1",
	},
	{
		link            = "[#234029:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2224",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#176598:Tattoo Extract]",
		author          = "Mike1955",
		xp              = "",
		new_xp          = "2333",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Insects",
		puzzle_type     = "1",
	},
	{
		link            = "[#234028:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2327",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#224298:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2396",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#224299:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2289",
		size            = "80x70",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#229935:\"Margie Thackeray\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2236",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#235780:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2498",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#228259:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2164",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#229934:\"Saint Agnes\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2242",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#125123:\"The Red and White Roses\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2308",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#229933:\"Cupid\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2649",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#136536:\"Little Margie\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2220",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#154188:\"Faith\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2121",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#154187:\"Study after manner of Francia\"(Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2173",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#124727:\"Angel of the Nativity\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2188",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#153736:\"The Whisper of the Muse\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2125",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#237090:Train Tunnel]",
		author          = "ChefSloth",
		xp              = "",
		new_xp          = "2100",
		size            = "80x80",
		category_1      = "Adventures",
		category_2      = "Transport",
		puzzle_type     = "1",
	},
	{
		link            = "[#232992:District 11 (The Hunger Games)]",
		author          = "erikarasik",
		xp              = "",
		new_xp          = "2187",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "Symbols",
		puzzle_type     = "3",
	},
	{
		link            = "[#236663:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2132",
		size            = "75x80",
		category_1      = "Anime",
		category_2      = "Unreal",
		puzzle_type     = "1",
	},
	{
		link            = "[#235820:Lollipop]",
		author          = "Goose1",
		xp              = "",
		new_xp          = "2235",
		size            = "80x80",
		category_1      = "Food",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#180148:Visigoth Warrior]",
		author          = "Anowyn",
		xp              = "",
		new_xp          = "2009",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "3",
	},
	{
		link            = "[#186824:Owl]",
		author          = "Bramati",
		xp              = "",
		new_xp          = "2122",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#151685:Dragon]",
		author          = "Yury_L",
		xp              = "",
		new_xp          = "2115",
		size            = "69x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#199546:Chlorella sp]",
		author          = "ima000",
		xp              = "",
		new_xp          = "2097",
		size            = "75x76",
		category_1      = "Plants",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#233584:Maximalist 125 - Dancing Dryads]",
		author          = "gattaccia",
		xp              = "",
		new_xp          = "2593",
		size            = "80x80",
		category_1      = "Fantasy",
		category_2      = "Unreal",
		puzzle_type     = "1",
	},
	{
		link            = "[#221944:Damsel in distress]",
		author          = "Jan Kokto",
		xp              = "",
		new_xp          = "2226",
		size            = "80x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#233179:Path from start to finish]",
		author          = "lost7153",
		xp              = "",
		new_xp          = "2391",
		size            = "80x80",
		category_1      = "Sport",
		category_2      = "Transport",
		puzzle_type     = "1",
	},
	{
		link            = "[#238685:Tape and Squares - BW]",
		author          = "Nononoobie",
		xp              = "",
		new_xp          = "2091",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#114845:Aiming]",
		author          = "belko61",
		xp              = "",
		new_xp          = "2008",
		size            = "75x80",
		category_1      = "People",
		category_2      = "Weapons",
		puzzle_type     = "1",
	},
	{
		link            = "[#213372:Fyodor Dostoevsky]",
		author          = "Glotecir",
		xp              = "2802",
		new_xp          = "2587",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "2",
	},
	{
		link            = "[#217408:Owl]",
		author          = "Glotecir",
		xp              = "2891",
		new_xp          = "2669",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#203841:Leopard]",
		author          = "Jan Kokto",
		xp              = "2710",
		new_xp          = "2484",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#227988:Into the Galaxy]",
		author          = "Argalum",
		xp              = "2443",
		new_xp          = "2255",
		size            = "80x80",
		category_1      = "Space",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#212549:Scrooge McDuck]",
		author          = "yagr",
		xp              = "2314",
		new_xp          = "2136",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Birds",
		puzzle_type     = "2",
	},
	{
		link            = "[#179770:Reflection in puddle]",
		author          = "iltarusko",
		xp              = "2905",
		new_xp          = "2682",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#182799:Loneliness]",
		author          = "iceeydasartes",
		xp              = "2341",
		new_xp          = "2161",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#184784:Sunrise at mountains]",
		author          = "iltarusko",
		xp              = "2683",
		new_xp          = "2477",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Twilight",
		puzzle_type     = "2",
	},
	{
		link            = "[#222459:Tom and Jerry]",
		author          = "yagr",
		xp              = "2777",
		new_xp          = "2563",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Animals",
		puzzle_type     = "2",
	},
	{
		link            = "[#221899:Optical Illusion]",
		author          = "han9102",
		xp              = "",
		new_xp          = "2091",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#216048:birds eye view]",
		author          = "QueenSteffinski",
		xp              = "",
		new_xp          = "2280",
		size            = "80x80",
		category_1      = "Houses",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#237768:Flying Duck]",
		author          = "ChefSloth",
		xp              = "",
		new_xp          = "2073",
		size            = "80x80",
		category_1      = "Birds",
		category_2      = "Nature",
		puzzle_type     = "2",
	},
	{
		link            = "[#205996:For all the comments]",
		author          = "Mike1955",
		xp              = "",
		new_xp          = "2102",
		size            = "80x80",
		category_1      = "Symbols",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#238700:Waves at sea (large version)]",
		author          = "Mind Freaq",
		xp              = "2294",
		new_xp          = "2214",
		size            = "80x79",
		category_1      = "Nature",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#218852:Hogwarts Crest]",
		author          = "ChefSloth",
		xp              = "2229",
		new_xp          = "2057",
		size            = "75x80",
		category_1      = "Fantasy",
		category_2      = "Symbols",
		puzzle_type     = "2",
	},
	{
		link            = "[#216427:German Shepard in a house]",
		author          = "Norg1308",
		xp              = "2355",
		new_xp          = "2174",
		size            = "75x80",
		category_1      = "Dogs",
		category_2      = "Objects",
		puzzle_type     = "2",
	},
	{
		link            = "[#208872:Punisher - Frank Castle]",
		author          = "Crep",
		xp              = "2231",
		new_xp          = "2045",
		size            = "77x80",
		category_1      = "Cartoon",
		category_2      = "Super",
		puzzle_type     = "3",
	},
	{
		link            = "[#142285:Pushkin, Russian poet]",
		author          = "Alexander Starkov",
		xp              = "2288",
		new_xp          = "2098",
		size            = "75x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "3",
	},
	{
		link            = "[#180070:Or Fredbear? Who cares it's a bear]",
		author          = "Psexanutik",
		xp              = "2429",
		new_xp          = "2242",
		size            = "80x80",
		category_1      = "Video",
		category_2      = "Unreal",
		puzzle_type     = "2",
	},
	{
		link            = "[#145682:Pokemon]",
		author          = "AJ7411",
		xp              = "2308",
		new_xp          = "2130",
		size            = "77x80",
		category_1      = "Super",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#146504:Animal]",
		author          = "AJ7411",
		xp              = "2379",
		new_xp          = "2196",
		size            = "71x80",
		category_1      = "Kawaii",
		category_2      = "Birds",
		puzzle_type     = "2",
	},
	{
		link            = "[#208156:Wolverine]",
		author          = "Crep",
		xp              = "2321",
		new_xp          = "2143",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Super",
		puzzle_type     = "2",
	},
	{
		link            = "[#205510:Liriodendron tulipifera]",
		author          = "ima000",
		xp              = "2211",
		new_xp          = "2041",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "Flowers",
		puzzle_type     = "2",
	},
	{
		link            = "[#196383:ONE PIECE - NIKA LUFFY]",
		author          = "ayakasumiria",
		xp              = "2366",
		new_xp          = "2184",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#184531:Discworld 29]",
		author          = "Lisenok_chiffa",
		xp              = "2341",
		new_xp          = "2160",
		size            = "80x70",
		category_1      = "Fantasy",
		category_2      = "People",
		puzzle_type     = "2",
	},
	{
		link            = "[#181511:Ant]",
		author          = "iltarusko",
		xp              = "2289",
		new_xp          = "2113",
		size            = "80x80",
		category_1      = "Insects",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#145495:Animal]",
		author          = "AJ7411",
		xp              = "2361",
		new_xp          = "2180",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#206777:Daredevil]",
		author          = "Crep",
		xp              = "2234",
		new_xp          = "2062",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Super",
		puzzle_type     = "2",
	},
	{
		link            = "[#207686:Koala with a eucalyptus branch]",
		author          = "Jan Kokto",
		xp              = "2229",
		new_xp          = "2057",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "Plants",
		puzzle_type     = "2",
	},
	{
		link            = "[#210955:The wolf (Well, wait!)]",
		author          = "yagr",
		xp              = "2243",
		new_xp          = "2071",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Animals",
		puzzle_type     = "2",
	},
	{
		link            = "[#209054:Norwegian forest cat]",
		author          = "yagr",
		xp              = "2228",
		new_xp          = "2057",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#237925:Dinner at the table]",
		author          = "artbyROO",
		xp              = "",
		new_xp          = "2163",
		size            = "80x80",
		category_1      = "Food",
		category_2      = "Objects",
		puzzle_type     = "3",
	},
	{
		link            = "[#218882:Tulips]",
		author          = "AV19",
		xp              = "",
		new_xp          = "2198",
		size            = "80x80",
		category_1      = "Flowers",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#208721:Different things 80x80]",
		author          = "Goose1",
		xp              = "2358",
		new_xp          = "2177",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "2",
	},
	{
		link            = "[#197175:Ateez hongjoong]",
		author          = "number10",
		xp              = "2415",
		new_xp          = "2229",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Music",
		puzzle_type     = "2",
	},
	{
		link            = "[#135892:Deadpool]",
		author          = "belko61",
		xp              = "2300",
		new_xp          = "2300",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#170616:500 Miles]",
		author          = "Fluffles",
		xp              = "2205",
		new_xp          = "2021",
		size            = "80x80",
		category_1      = "Music",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#189331:Astronaut]",
		author          = "simsomyung",
		xp              = "2348",
		new_xp          = "2167",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Space",
		puzzle_type     = "2",
	},
	{
		link            = "[#176305:Asta]",
		author          = "the agreste",
		xp              = "2366",
		new_xp          = "2184",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#208023:Tirano-ZAD]",
		author          = "Goose1",
		xp              = "2257",
		new_xp          = "2069",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "Games",
		puzzle_type     = "3",
	},
	{
		link            = "[#191596:Quaders]",
		author          = "Effti",
		xp              = "",
		new_xp          = "2102",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "Symbols",
		puzzle_type     = "2",
	},
	{
		link            = "[#148461:Gogeta]",
		author          = "AJ7411",
		xp              = "2276",
		new_xp          = "2276",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#184366:Claw]",
		author          = "AJ7411",
		xp              = "2003",
		new_xp          = "2003",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Animals",
		puzzle_type     = "1",
	},
	{
		link            = "[#92161:Happy Victory!]",
		author          = "belko61",
		xp              = "",
		new_xp          = "2233",
		size            = "80x70",
		category_1      = "People",
		category_2      = "Holidays",
		puzzle_type     = "1",
	},
	{
		link            = "[#59652:Girl]",
		author          = "belko61",
		xp              = "",
		new_xp          = "2202",
		size            = "75x80",
		category_1      = "People",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#238197:2 in 1 series]",
		author          = "mortyrus",
		xp              = "",
		new_xp          = "2213",
		size            = "80x80",
		category_1      = "Games",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#223372:Mushroom Power]",
		author          = "Mushroom-World",
		xp              = "2324",
		new_xp          = "2112",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "Designs",
		puzzle_type     = "3",
	},
	{
		link            = "[#208375:Thor]",
		author          = "Crep",
		xp              = "2281",
		new_xp          = "2091",
		size            = "74x80",
		category_1      = "Cartoon",
		category_2      = "Super",
		puzzle_type     = "3",
	},
	{
		link            = "[#145316:7DB]",
		author          = "AJ7411",
		xp              = "",
		new_xp          = "2030",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#237026:Sleep in the Mountains 2]",
		author          = "ChefSloth",
		xp              = "",
		new_xp          = "2271",
		size            = "80x80",
		category_1      = "Nature",
		category_2      = "Adventures",
		puzzle_type     = "2",
	},
	{
		link            = "[#236138:Cryptic french love message]",
		author          = "Passworld",
		xp              = "",
		new_xp          = "2383",
		size            = "80x80",
		category_1      = "Symbols",
		category_2      = "Love",
		puzzle_type     = "2",
	},
	{
		link            = "[#231426:Nausicaa of the Valley of the Wind MANGA]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2407",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#236966:Quilt]",
		author          = "Hammurabi",
		xp              = "",
		new_xp          = "2449",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "4",
	},
	{
		link            = "[#222433:MyDesign4]",
		author          = "JACK4L",
		xp              = "",
		new_xp          = "2392",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#237489:Swag]",
		author          = "yongkamii",
		xp              = "",
		new_xp          = "2555",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#239780:Black glasses]",
		author          = "Jan Kokto",
		xp              = "",
		new_xp          = "2075",
		size            = "72x80",
		category_1      = "People",
		category_2      = "Clothes",
		puzzle_type     = "3",
	},
	{
		link            = "[#237674:\"Blessing and Blessed\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2279",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#230040:2 in 1 series]",
		author          = "mortyrus",
		xp              = "",
		new_xp          = "2114",
		size            = "80x80",
		category_1      = "Egypt",
		category_2      = "Games",
		puzzle_type     = "1",
	},
	{
		link            = "[#239188:Slot-machine]",
		author          = "Goose1",
		xp              = "",
		new_xp          = "2941",
		size            = "75x80",
		category_1      = "Games",
		category_2      = "Objects",
		puzzle_type     = "2",
	},
	{
		link            = "[#222033:MyDesign3]",
		author          = "JACK4L",
		xp              = "",
		new_xp          = "2155",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#217145:TETRIS]",
		author          = "Jose L. Gamez",
		xp              = "",
		new_xp          = "2060",
		size            = "80x80",
		category_1      = "Video",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#212409:Manul]",
		author          = "yagr",
		xp              = "",
		new_xp          = "2141",
		size            = "80x80",
		category_1      = "Cats",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#212686:Psihichnii rozlad]",
		author          = "Goose1",
		xp              = "",
		new_xp          = "2609",
		size            = "80x80",
		category_1      = "Smiles",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#227887:Samurai Pizza Cats]",
		author          = "yagr",
		xp              = "",
		new_xp          = "2325",
		size            = "80x80",
		category_1      = "Kawaii",
		category_2      = "Cats",
		puzzle_type     = "2",
	},
	{
		link            = "[#222479:Yep.]",
		author          = "Organical Mechanical",
		xp              = "",
		new_xp          = "2592",
		size            = "80x80",
		category_1      = "Video",
		category_2      = "Games",
		puzzle_type     = "3",
	},
	{
		link            = "[#224273:Hunter x Hunter - Ponzu]",
		author          = "NNP",
		xp              = "",
		new_xp          = "2115",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#212844:Gadget]",
		author          = "yagr",
		xp              = "",
		new_xp          = "2377",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Animals",
		puzzle_type     = "2",
	},
	{
		link            = "[#213614:Hungry Sloth]",
		author          = "ChefSloth",
		xp              = "",
		new_xp          = "2131",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#213849:House plants]",
		author          = "artbyROO",
		xp              = "",
		new_xp          = "2196",
		size            = "80x80",
		category_1      = "Plants",
		category_2      = "Objects",
		puzzle_type     = "3",
	},
	{
		link            = "[#214854:Edgar Allan Poe]",
		author          = "Dimsum",
		xp              = "",
		new_xp          = "2287",
		size            = "80x75",
		category_1      = "Fantasy",
		category_2      = "Birds",
		puzzle_type     = "2",
	},
	{
		link            = "[#213690:Zodiac]",
		author          = "icspn",
		xp              = "",
		new_xp          = "2738",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "History",
		puzzle_type     = "2",
	},
	{
		link            = "[#191387:OMMM 2]",
		author          = "ZYANKALIA",
		xp              = "",
		new_xp          = "2560",
		size            = "80x80",
		category_1      = "Symbols",
		category_2      = "Horoscope",
		puzzle_type     = "2",
	},
	{
		link            = "[#136650:Milize Vladilena]",
		author          = "rphii",
		xp              = "",
		new_xp          = "2310",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#192694:Octavinel Armband]",
		author          = "Kantokusei",
		xp              = "",
		new_xp          = "2391",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Symbols",
		puzzle_type     = "2",
	},
	{
		link            = "[#137697:Deers]",
		author          = "chibis",
		xp              = "",
		new_xp          = "2012",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#215507:Jim Carrey ( Cartoon )]",
		author          = "Ozhegov",
		xp              = "",
		new_xp          = "2479",
		size            = "80x80",
		category_1      = "Movies",
		category_2      = "People",
		puzzle_type     = "2",
	},
	{
		link            = "[#218394:Cult of Cthulhu]",
		author          = "ChefSloth",
		xp              = "",
		new_xp          = "2435",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#200048:triple flowers]",
		author          = "Jir",
		xp              = "",
		new_xp          = "2430",
		size            = "80x80",
		category_1      = "Flowers",
		category_2      = "",
		puzzle_type     = "2",
	},
	{
		link            = "[#181660:Two little guys]",
		author          = "iltarusko",
		xp              = "",
		new_xp          = "2331",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Nature",
		puzzle_type     = "2",
	},
	{
		link            = "[#211460:Hoya flower]",
		author          = "JayCee_Sw",
		xp              = "",
		new_xp          = "2679",
		size            = "80x80",
		category_1      = "Flowers",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#208470:Messy sketch]",
		author          = "iltarusko",
		xp              = "",
		new_xp          = "2587",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Painting",
		puzzle_type     = "2",
	},
	{
		link            = "[#215139:St. Anger Metallica]",
		author          = "Ossian",
		xp              = "",
		new_xp          = "2719",
		size            = "80x80",
		category_1      = "Symbols",
		category_2      = "Music",
		puzzle_type     = "2",
	},
	{
		link            = "[#213940:Dan dadan - \"MOMO\" Ayase]",
		author          = "ayakasumiria",
		xp              = "",
		new_xp          = "2613",
		size            = "80x80",
		category_1      = "Kawaii",
		category_2      = "Anime",
		puzzle_type     = "2",
	},
	{
		link            = "[#215900:Plague Doctor]",
		author          = "ChefSloth",
		xp              = "",
		new_xp          = "2718",
		size            = "80x80",
		category_1      = "History",
		category_2      = "Science",
		puzzle_type     = "3",
	},
	{
		link            = "[#182512:Shakti, the Universal Mother]",
		author          = "Anowyn",
		xp              = "",
		new_xp          = "2208",
		size            = "80x80",
		category_1      = "Around",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#181734:dragon chinois affam]",
		author          = "iceeydasartes",
		xp              = "",
		new_xp          = "2097",
		size            = "80x80",
		category_1      = "Dragons",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#201770:Farm]",
		author          = "Mike1955",
		xp              = "",
		new_xp          = "2046",
		size            = "80x80",
		category_1      = "Animals",
		category_2      = "Machines",
		puzzle_type     = "1",
	},
	{
		link            = "[#124983:\"I wait\" (Cameron)]",
		author          = "Lysy Jan FOX",
		xp              = "",
		new_xp          = "2004",
		size            = "80x80",
		category_1      = "People",
		category_2      = "History",
		puzzle_type     = "1",
	},
	{
		link            = "[#96610:True Nonoception]",
		author          = "PQR",
		xp              = "2492",
		new_xp          = "2492",
		size            = "80x80",
		category_1      = "Video",
		category_2      = "Animals",
		puzzle_type     = "1",
	},
	{
		link            = "[#31929:Souryuu Asuka Langley]",
		author          = "itsuki-ogre",
		xp              = "2282",
		new_xp          = "2282",
		size            = "80x80",
		category_1      = "Anime",
		category_2      = "",
		puzzle_type     = "1",
	},
	{
		link            = "[#207171:Tiger]",
		author          = "AJ7411",
		xp              = "2153",
		new_xp          = "2153",
		size            = "80x80",
		category_1      = "Kawaii",
		category_2      = "Animals",
		puzzle_type     = "1",
	},
	{
		link            = "[#213590:Teddybear]",
		author          = "artbyROO",
		xp              = "2210",
		new_xp          = "2040",
		size            = "80x80",
		category_1      = "Kawaii",
		category_2      = "Animals",
		puzzle_type     = "2",
	},
	{
		link            = "[#240526:Samurai]",
		author          = "Bramati",
		xp              = "",
		new_xp          = "2019",
		size            = "80x78",
		category_1      = "People",
		category_2      = "Weapons",
		puzzle_type     = "2",
	},
	{
		link            = "[#179642:Romeo and Juliet]",
		author          = "Anowyn",
		xp              = "",
		new_xp          = "2200",
		size            = "80x80",
		category_1      = "People",
		category_2      = "Love",
		puzzle_type     = "1",
	},
	{
		link            = "[#156160:Monarch]",
		author          = "Cubie",
		xp              = "",
		new_xp          = "2119",
		size            = "80x80",
		category_1      = "Unreal",
		category_2      = "Insects",
		puzzle_type     = "1",
	},
	{
		link            = "[#44808:Girl]",
		author          = "LUNA-CROIX",
		xp              = "",
		new_xp          = "2143",
		size            = "80x80",
		category_1      = "Kawaii",
		category_2      = "People",
		puzzle_type     = "2",
	},
	{
		link            = "[#147168:Animal]",
		author          = "AJ7411",
		xp              = "",
		new_xp          = "2173",
		size            = "80x80",
		category_1      = "Kawaii",
		category_2      = "Animals",
		puzzle_type     = "2",
	},
	{
		link            = "[#207770:Little mermaid]",
		author          = "kaatkaa7",
		xp              = "",
		new_xp          = "2254",
		size            = "80x80",
		category_1      = "Cartoon",
		category_2      = "Fantasy",
		puzzle_type     = "3",
	},
	{
		link            = "[#240587:Surfer]",
		author          = "JayCee_Sw",
		xp              = "",
		new_xp          = "2461",
		size            = "80x80",
		category_1      = "Sport",
		category_2      = "",
		puzzle_type     = "3",
	},
	{
		link            = "[#177248:pirogom-003]",
		author          = "PiroGom",
		xp              = "",
		new_xp          = "2094",
		size            = "80x80",
		category_1      = "Designs",
		category_2      = "",
		puzzle_type     = "1",
	},
	-- Placeholder (for copy-pasting).
	{
		link            = "",
		author          = "",
		xp              = "",
		new_xp          = "",
		size            = "",
		category_1      = "",
		category_2      = "",
		puzzle_type     = "",
	},
}

return nonograms
